"""The synthetic PDF regression corpus.

Every fixture is generated from code in this package: no document in the
corpus is copied from a customer, an applicant, or the internet. Visible text
uses the word SYNTHETIC and invented values so that any extract of a fixture
is recognizable as test data.

Each ``FixtureSpec`` records the fixture's intent, the validation-matrix
family it serves (docs/product/VALIDATION.md section 2), the document
features it carries, and the behavior of the baseline ``pdf_compressor.py``
it is meant to capture.
"""

from __future__ import annotations

import hashlib
import io
import random
from dataclasses import dataclass
from functools import lru_cache
from typing import Callable

from PIL import Image, ImageDraw, ImageFilter, ImageFont
from pypdf import PdfReader, PdfWriter

from .pdfbuild import (
    A4,
    LETTER,
    LETTER_LANDSCAPE,
    Document,
    Name,
    Raw,
    Ref,
    Stream,
    TextLine,
    draw_image,
    font_resources,
    info_dictionary,
    jpeg_image,
    text_operators,
)
from .signing import detached_pkcs7

SYNTHETIC_MARKER = "SYNTHETIC"
USER_PASSWORD = "synthetic-user-password"
OWNER_PASSWORD = "synthetic-owner-password"
PROVENANCE = (
    "Generated by tests/corpus (CHONK synthetic test corpus); no external inputs; "
    "all names, numbers, and images are invented."
)


@dataclass(frozen=True)
class FixtureSpec:
    name: str
    family: str
    intent: str
    features: tuple[str, ...]
    has_text_layer: bool
    baseline: str
    # Whether baseline pdf_compressor.py writes an output for this fixture
    # when the size ceiling is generous (ten times the input size).
    baseline_accepts: bool
    build: Callable[[], bytes]
    # Expected preflight decision under the default policy
    # (preserve-existing-text-v1): "supported", "blocked" (a feature the policy
    # blocks is present), "inconclusive" (inspection cannot rule a blocked
    # feature out), or "unreadable" (not a readable PDF).
    preflight: str = "supported"

    @property
    def filename(self) -> str:
        return f"{self.name}.pdf"


# --------------------------------------------------------------------------
# Building blocks
# --------------------------------------------------------------------------


def _file_id(name: str) -> bytes:
    return hashlib.md5(f"chonk-fixture:{name}".encode("ascii")).digest()


@dataclass
class PageSpec:
    content: bytes
    size: tuple[float, float] = LETTER
    rotate: int = 0
    images: dict[str, Ref] | None = None
    annotations: list[Ref] | None = None
    resources: dict | None = None
    extra: dict | None = None


def _assemble(
    name: str,
    title: str,
    pages: list[PageSpec],
    document: Document | None = None,
    fonts: dict[str, Ref] | None = None,
    catalog_extra: dict | None = None,
    page_refs: list[Ref] | None = None,
) -> bytes:
    document = document or Document()
    fonts = fonts or font_resources(document)
    pages_ref = document.reserve()
    page_refs = page_refs or [document.reserve() for _ in pages]
    for page_ref, page in zip(page_refs, pages):
        content_ref = document.add(Stream({}, page.content))
        resources: dict = {"Font": dict(fonts)}
        if page.images:
            resources["XObject"] = dict(page.images)
        resources.update(page.resources or {})
        entries: dict = {
            "Type": Name("Page"),
            "Parent": pages_ref,
            "MediaBox": [0, 0, page.size[0], page.size[1]],
            "Resources": resources,
            "Contents": content_ref,
        }
        if page.rotate:
            entries["Rotate"] = page.rotate
        if page.annotations:
            entries["Annots"] = list(page.annotations)
        entries.update(page.extra or {})
        document.set(page_ref, entries)
    document.set(
        pages_ref, {"Type": Name("Pages"), "Kids": list(page_refs), "Count": len(pages)}
    )
    catalog: dict = {"Type": Name("Catalog"), "Pages": pages_ref}
    catalog.update(catalog_extra or {})
    root = document.add(catalog)
    return document.to_bytes(root, _file_id(name), info_dictionary(document, title))


def _heading(text: str, y: float, x: float = 72) -> TextLine:
    return TextLine(x, y, 18, text, "F4")


def _marker_line(page_label: str) -> TextLine:
    return TextLine(72, 36, 8, f"{SYNTHETIC_MARKER} test document - {page_label}", "F1")


def _rule(x1: float, y1: float, x2: float, y2: float, width: float = 1.0) -> bytes:
    return f"q {width} w {x1} {y1} m {x2} {y2} l S Q\n".encode("ascii")


def _box(x: float, y: float, w: float, h: float, gray: float) -> bytes:
    return f"q {gray} g {x} {y} {w} {h} re f Q\n".encode("ascii")


def _statement_page(seed: int, page_label: str) -> bytes:
    """A text-only page resembling a statement: prose, a table, rules."""
    rng = random.Random(seed)
    lines = [
        _heading(f"{SYNTHETIC_MARKER} Account Statement {seed:04d}", 720),
        TextLine(72, 696, 11, "Prepared for: Synthetic Person, 1 Example Street, Testville", "F3"),
        TextLine(72, 681, 11, f"Statement period: 2026-01-01 to 2026-01-31 (ref {seed:06d})", "F3"),
    ]
    y = 640.0
    lines.append(TextLine(72, y, 10, "Date        Description                    Amount", "F2"))
    total = 0
    for row in range(14):
        y -= 16
        amount = rng.randrange(100, 99_999)
        total += amount
        lines.append(
            TextLine(
                72,
                y,
                10,
                f"2026-01-{row + 2:02d}  Synthetic item {rng.randrange(1000, 9999)}"
                f"          {amount / 100:>10,.2f}",
                "F2",
            )
        )
    y -= 24
    lines.append(TextLine(72, y, 11, f"Total due: {total / 100:,.2f}", "F4"))
    lines.append(
        TextLine(72, y - 30, 10, "This page is synthetic. Figures come from a fixed seed so that", "F1")
    )
    lines.append(
        TextLine(72, y - 44, 10, "a digit changed during compression can be detected.", "F1")
    )
    lines.append(_marker_line(page_label))
    return (
        text_operators(lines)
        + _rule(72, 652, 540, 652, 0.75)
        + _rule(72, y + 14, 540, y + 14, 0.5)
    )


def _scan_image(seed: int, width: int, height: int, lines: list[str]) -> Image.Image:
    """A grayscale 'scanned page': paper tone, grain, and bitmap text."""
    rng = random.Random(seed)
    paper = Image.linear_gradient("L").resize((width, height)).point(
        lambda v: 236 + v // 24
    )
    grain = Image.frombytes("L", (width, height), rng.randbytes(width * height))
    grain = grain.filter(ImageFilter.GaussianBlur(1.2)).point(lambda v: 128 + (v - 128) // 3)
    page = Image.blend(paper, grain, 0.25)

    # Draw at low resolution, then scale up to mimic scanned glyph edges.
    small = Image.new("L", (width // 3, height // 3), 255)
    draw = ImageDraw.Draw(small)
    font = ImageFont.load_default()
    y = 30
    for line in lines:
        draw.text((24, y), line, fill=20, font=font)
        y += 16
    ink = small.resize((width, height), Image.Resampling.BILINEAR)
    return Image.composite(page, ink, ink.point(lambda v: 255 if v > 200 else 0))


def _photo_image(seed: int, width: int, height: int) -> Image.Image:
    """An RGB 'photograph': gradients, shapes, and fine texture."""
    rng = random.Random(seed)
    red = Image.linear_gradient("L").resize((width, height))
    green = Image.radial_gradient("L").resize((width, height))
    blue = Image.linear_gradient("L").rotate(90).resize((width, height))
    image = Image.merge("RGB", (red, green, blue))
    draw = ImageDraw.Draw(image)
    for _ in range(40):
        x, y = rng.randrange(width), rng.randrange(height)
        r = rng.randrange(8, width // 6)
        color = (rng.randrange(256), rng.randrange(256), rng.randrange(256))
        draw.ellipse((x - r, y - r, x + r, y + r), outline=color, width=3)
    texture = Image.frombytes("RGB", (width, height), rng.randbytes(width * height * 3))
    return Image.blend(image, texture.filter(ImageFilter.GaussianBlur(0.8)), 0.18)


def _jpeg(image: Image.Image, quality: int) -> bytes:
    buffer = io.BytesIO()
    image.save(buffer, format="JPEG", quality=quality, subsampling=0, optimize=False)
    return buffer.getvalue()


# --------------------------------------------------------------------------
# Fixture builders
# --------------------------------------------------------------------------


def build_text_statement() -> bytes:
    return _assemble(
        "text-statement",
        "SYNTHETIC text statement",
        [PageSpec(_statement_page(1, "page 1 of 1"))],
    )


def _multipage_pages() -> list[PageSpec]:
    sizes = [LETTER] * 12
    sizes[3] = A4
    sizes[6] = LETTER_LANDSCAPE
    rotations = [0] * 12
    rotations[9] = 90
    pages = []
    for index in range(12):
        label = f"page {index + 1} of 12"
        content = _statement_page(100 + index, label)
        content += text_operators([TextLine(460, 760, 12, f"Page {index + 1} / 12", "F4")])
        if sizes[index] == LETTER_LANDSCAPE:
            # Scale the portrait layout so nothing falls outside the MediaBox.
            content = b"q 0.75 0 0 0.75 166.5 9 cm\n" + content + b"Q\n"
        pages.append(PageSpec(content, size=sizes[index], rotate=rotations[index]))
    return pages


def build_text_multipage() -> bytes:
    """Twelve pages with distinct content and mixed geometry."""
    return _assemble("text-multipage", "SYNTHETIC twelve-page statement", _multipage_pages())


def build_outline() -> bytes:
    """The twelve-page statement with a two-entry outline (bookmarks)."""
    pages = _multipage_pages()
    document = Document()
    fonts = font_resources(document)
    page_refs = [document.reserve() for _ in pages]
    outlines = document.reserve()
    first = document.reserve()
    second = document.reserve()
    document.set(
        first,
        {"Title": "Synthetic section A", "Parent": outlines, "Next": second,
         "Dest": [page_refs[0], Name("Fit")]},
    )
    document.set(
        second,
        {"Title": "Synthetic section B", "Parent": outlines, "Prev": first,
         "Dest": [page_refs[6], Name("Fit")]},
    )
    document.set(
        outlines, {"Type": Name("Outlines"), "First": first, "Last": second, "Count": 2}
    )
    return _assemble(
        "outline",
        "SYNTHETIC statement with outline",
        pages,
        document=document,
        fonts=fonts,
        catalog_extra={"Outlines": outlines, "PageMode": Name("UseOutlines")},
        page_refs=page_refs,
    )


def build_text_tiny() -> bytes:
    """Small type, hairlines, and a barcode-like pattern (local detail)."""
    rng = random.Random(7)
    lines = [_heading(f"{SYNTHETIC_MARKER} fine print sample", 720)]
    y = 690.0
    for size in (6, 5, 4.5, 4, 3.5):
        for _ in range(3):
            digits = " ".join(f"{rng.randrange(10_000):04d}" for _ in range(6))
            lines.append(TextLine(72, y, size, f"{size}pt ref {digits}", "F1"))
            y -= size + 3
        y -= 6
    lines.append(
        TextLine(72, y - 10, 5, "Footnote 1: SYNTHETIC terms apply to invented accounts only.", "F3")
    )
    lines.append(_marker_line("page 1 of 1"))
    content = text_operators(lines)
    for i in range(30):
        content += _rule(72, 420 - i * 4, 300, 420 - i * 4, 0.1 + (i % 5) * 0.05)
    x = 340.0
    for _ in range(70):
        width = rng.choice((0.5, 0.75, 1.0, 1.5, 2.0))
        content += _box(x, 300, width, 120, 0)
        x += width + rng.choice((0.5, 1.0, 1.5))
    return _assemble("text-tiny", "SYNTHETIC fine print", [PageSpec(content)])


def build_image_scan() -> bytes:
    """Two image-only pages with no text layer, like a scanner's output."""
    document = Document()
    fonts = font_resources(document)
    pages = []
    for index in range(2):
        width, height = 1275, 1650  # US Letter at 150 dpi
        image = _scan_image(
            200 + index,
            width,
            height,
            [f"{SYNTHETIC_MARKER} SCANNED LETTER {index + 1}/2"]
            + [f"Line {n:02d}: invented figure {1000 + 37 * n + index}" for n in range(24)],
        )
        ref = jpeg_image(document, _jpeg(image, 90), width, height, "L")
        pages.append(PageSpec(draw_image("Im1", 0, 0, *LETTER), images={"Im1": ref}))
    return _assemble("image-scan", "SYNTHETIC scan", pages, document=document, fonts=fonts)


def build_image_mixed() -> bytes:
    """Text with an embedded photograph on each of two pages."""
    document = Document()
    fonts = font_resources(document)
    pages = []
    for index in range(2):
        width, height = 900, 600
        ref = jpeg_image(document, _jpeg(_photo_image(300 + index, width, height), 92), width, height, "RGB")
        content = draw_image("Im1", 72, 330, 468, 312)
        content += text_operators(
            [
                _heading(f"{SYNTHETIC_MARKER} site report {index + 1}", 720),
                TextLine(72, 300, 11, "Figure 1: invented photograph for compression tests.", "F3"),
                TextLine(72, 280, 11, f"Inspection number {7100 + index}; reading 42.{index}7 units.", "F1"),
                _marker_line(f"page {index + 1} of 2"),
            ]
        )
        pages.append(PageSpec(content, images={"Im1": ref}))
    return _assemble("image-mixed", "SYNTHETIC mixed", pages, document=document, fonts=fonts)


def build_already_small() -> bytes:
    content = text_operators(
        [
            _heading(f"{SYNTHETIC_MARKER} note", 720),
            TextLine(72, 690, 11, "Balance 12.34 on 2026-01-05.", "F1"),
            _marker_line("page 1 of 1"),
        ]
    )
    return _assemble("already-small", "SYNTHETIC small note", [PageSpec(content)])


def _encrypt(plain: bytes, user_password: str) -> bytes:
    """RC4-128 keeps output reproducible: AES would draw random IVs."""
    writer = PdfWriter(clone_from=PdfReader(io.BytesIO(plain)))
    writer.encrypt(
        user_password=user_password,
        owner_password=OWNER_PASSWORD,
        algorithm="RC4-128",
    )
    buffer = io.BytesIO()
    writer.write(buffer)
    return buffer.getvalue()


def build_encrypted_user_password() -> bytes:
    return _encrypt(build_already_small(), USER_PASSWORD)


def build_encrypted_owner_only() -> bytes:
    """Encrypted with an empty user password: opens without prompting."""
    return _encrypt(build_already_small(), "")


def build_form() -> bytes:
    document = Document()
    fonts = font_resources(document)
    page_ref = document.reserve()

    name_appearance = document.add(
        Stream(
            {
                "Type": Name("XObject"),
                "Subtype": Name("Form"),
                "BBox": [0, 0, 250, 20],
                "Resources": {"Font": {"F1": fonts["F1"]}},
            },
            b"/Tx BMC BT /F1 11 Tf 2 6 Td (Synthetic Person) Tj ET EMC",
        )
    )
    name_field = document.add(
        {
            "Type": Name("Annot"),
            "Subtype": Name("Widget"),
            "FT": Name("Tx"),
            "T": "applicant_name",
            "V": "Synthetic Person",
            "DA": "/F1 11 Tf 0 g",
            "Rect": [200, 640, 450, 660],
            "F": 4,
            "P": page_ref,
            "AP": {"N": name_appearance},
        }
    )
    checked = document.add(
        Stream(
            {"Type": Name("XObject"), "Subtype": Name("Form"), "BBox": [0, 0, 14, 14]},
            b"0 g 2 2 10 10 re f",
        )
    )
    unchecked = document.add(
        Stream({"Type": Name("XObject"), "Subtype": Name("Form"), "BBox": [0, 0, 14, 14]}, b"")
    )
    checkbox = document.add(
        {
            "Type": Name("Annot"),
            "Subtype": Name("Widget"),
            "FT": Name("Btn"),
            "T": "consent_synthetic",
            "V": Name("Yes"),
            "AS": Name("Yes"),
            "Rect": [200, 600, 214, 614],
            "F": 4,
            "P": page_ref,
            "AP": {"N": {"Yes": checked, "Off": unchecked}},
        }
    )
    content = text_operators(
        [
            _heading(f"{SYNTHETIC_MARKER} application form", 720),
            TextLine(72, 646, 11, "Applicant name:", "F1"),
            TextLine(72, 603, 11, "Consent given:", "F1"),
            _marker_line("page 1 of 1"),
        ]
    ) + b"q 0.5 w 200 640 250 20 re S 200 600 14 14 re S Q\n"
    acroform = document.add(
        {
            "Fields": [name_field, checkbox],
            "DA": "/F1 11 Tf 0 g",
            "DR": {"Font": {"F1": fonts["F1"]}},
        }
    )
    return _assemble(
        "form-acroform",
        "SYNTHETIC form",
        [PageSpec(content, annotations=[name_field, checkbox])],
        document=document,
        fonts=fonts,
        catalog_extra={"AcroForm": acroform},
        page_refs=[page_ref],
    )


def build_annotations() -> bytes:
    document = Document()
    fonts = font_resources(document)
    page_ref = document.reserve()
    link = document.add(
        {
            "Type": Name("Annot"),
            "Subtype": Name("Link"),
            "Rect": [72, 676, 300, 692],
            "Border": [0, 0, 0],
            "A": {"S": Name("URI"), "URI": "https://example.invalid/synthetic"},
        }
    )
    note = document.add(
        {
            "Type": Name("Annot"),
            "Subtype": Name("Text"),
            "Rect": [400, 700, 420, 720],
            "Contents": "SYNTHETIC reviewer note: verify invented total.",
            "T": "Synthetic Reviewer",
            "Open": False,
            "F": 4,
        }
    )
    highlight = document.add(
        {
            "Type": Name("Annot"),
            "Subtype": Name("Highlight"),
            "Rect": [70, 640, 260, 656],
            "QuadPoints": [70, 656, 260, 656, 70, 640, 260, 640],
            "C": [1, 1, 0],
            "Contents": "SYNTHETIC highlight",
            "F": 4,
        }
    )
    content = text_operators(
        [
            _heading(f"{SYNTHETIC_MARKER} annotated page", 720),
            TextLine(72, 680, 11, "Link: example.invalid/synthetic", "F1"),
            TextLine(72, 644, 11, "Highlighted total: 4,321.00", "F1"),
            _marker_line("page 1 of 1"),
        ]
    )
    return _assemble(
        "annotations",
        "SYNTHETIC annotations",
        [PageSpec(content, annotations=[link, note, highlight])],
        document=document,
        fonts=fonts,
        page_refs=[page_ref],
    )


SIGNATURE_HEX_CAPACITY = 8_192
_BYTE_RANGE_PLACEHOLDER = b"[0 0000000000 0000000000 0000000000]"


def build_signed() -> bytes:
    """An approval signature (adbe.pkcs7.detached) by the disposable signer."""
    document = Document()
    fonts = font_resources(document)
    page_ref = document.reserve()
    signature = document.add(
        {
            "Type": Name("Sig"),
            "Filter": Name("Adobe.PPKLite"),
            "SubFilter": Name("adbe.pkcs7.detached"),
            "ByteRange": Raw(_BYTE_RANGE_PLACEHOLDER),
            "Contents": Raw(b"<" + b"0" * SIGNATURE_HEX_CAPACITY + b">"),
            "M": "D:20260101000000Z",
            "Name": "CHONK disposable test signer",
            "Reason": "SYNTHETIC fixture: signature-bearing input",
        }
    )
    field = document.add(
        {
            "Type": Name("Annot"),
            "Subtype": Name("Widget"),
            "FT": Name("Sig"),
            "T": "synthetic_signature",
            "V": signature,
            "Rect": [0, 0, 0, 0],
            "F": 132,
            "P": page_ref,
        }
    )
    acroform = document.add({"Fields": [field], "SigFlags": 3})
    content = text_operators(
        [
            _heading(f"{SYNTHETIC_MARKER} signed agreement", 720),
            TextLine(72, 690, 11, "Agreed amount: 2,500.00 (invented).", "F1"),
            _marker_line("page 1 of 1"),
        ]
    )
    unsigned = _assemble(
        "signed-pkcs7",
        "SYNTHETIC signed",
        [PageSpec(content, annotations=[field])],
        document=document,
        fonts=fonts,
        catalog_extra={"AcroForm": acroform},
        page_refs=[page_ref],
    )

    contents_start = unsigned.index(b"<" + b"0" * SIGNATURE_HEX_CAPACITY + b">")
    contents_end = contents_start + SIGNATURE_HEX_CAPACITY + 2
    byte_range = (0, contents_start, contents_end, len(unsigned) - contents_end)
    placed = f"[0 {byte_range[1]:010d} {byte_range[2]:010d} {byte_range[3]:010d}]".encode("ascii")
    assert len(placed) == len(_BYTE_RANGE_PLACEHOLDER)
    prepared = unsigned.replace(_BYTE_RANGE_PLACEHOLDER, placed, 1)
    signed_data = prepared[:contents_start] + prepared[contents_end:]
    der = detached_pkcs7(signed_data)
    hex_signature = der.hex().upper().encode("ascii")
    if len(hex_signature) > SIGNATURE_HEX_CAPACITY:
        raise ValueError("signature placeholder is too small")
    hex_signature = hex_signature.ljust(SIGNATURE_HEX_CAPACITY, b"0")
    return prepared[: contents_start + 1] + hex_signature + prepared[contents_end - 1 :]


def _note_page(title: str, *lines: str) -> bytes:
    """A short text page: a heading, body lines, and the synthetic marker."""
    body = [TextLine(72, 690 - 16 * index, 11, line, "F1") for index, line in enumerate(lines)]
    return text_operators([_heading(f"{SYNTHETIC_MARKER} {title}", 720), *body, _marker_line("page 1 of 1")])


def build_xfa_form() -> bytes:
    """An AcroForm that also carries an XFA form description."""
    document = Document()
    fonts = font_resources(document)
    page_ref = document.reserve()
    field = document.add(
        {
            "Type": Name("Annot"),
            "Subtype": Name("Widget"),
            "FT": Name("Tx"),
            "T": "reference_synthetic",
            "V": "SYN-0001",
            "Rect": [200, 640, 450, 660],
            "F": 4,
            "P": page_ref,
        }
    )
    xdp = document.add(
        Stream(
            {},
            b'<?xml version="1.0" encoding="UTF-8"?>\n'
            b'<xdp:xdp xmlns:xdp="http://ns.adobe.com/xdp/">'
            b'<template xmlns="http://www.xfa.org/schema/xfa-template/3.3/">'
            b'<subform name="SYNTHETIC"><field name="reference_synthetic"/></subform>'
            b"</template></xdp:xdp>\n",
        )
    )
    acroform = document.add({"Fields": [field], "XFA": xdp, "DA": "/F1 11 Tf 0 g"})
    return _assemble(
        "xfa-form",
        "SYNTHETIC XFA form",
        [PageSpec(_note_page("XFA form", "Reference:"), annotations=[field])],
        document=document,
        fonts=fonts,
        catalog_extra={"AcroForm": acroform},
        page_refs=[page_ref],
    )


def _javascript(document: Document, source: str) -> Ref:
    return document.add({"S": Name("JavaScript"), "JS": source})


def build_javascript_document() -> bytes:
    """Document-level JavaScript: a name-tree script and an open action."""
    document = Document()
    fonts = font_resources(document)
    named = _javascript(document, "/* SYNTHETIC */ var chonkFixture = 1;")
    opener = _javascript(document, "/* SYNTHETIC */ app.alert('synthetic');")
    names = document.add({"JavaScript": {"Names": ["synthetic-script", named]}})
    return _assemble(
        "javascript-document",
        "SYNTHETIC document JavaScript",
        [PageSpec(_note_page("scripted document", "Opening this file runs a script."))],
        document=document,
        fonts=fonts,
        catalog_extra={"Names": names, "OpenAction": opener},
    )


def build_page_open_action() -> bytes:
    """A page additional-action (/AA /O) that launches an application."""
    document = Document()
    fonts = font_resources(document)
    launch = document.add({"S": Name("Launch"), "F": "synthetic-program.invalid"})
    return _assemble(
        "page-open-action",
        "SYNTHETIC page action",
        [PageSpec(
            _note_page("page action", "Opening this page requests a program launch."),
            extra={"AA": {"O": launch}},
        )],
        document=document,
        fonts=fonts,
    )


def build_embedded_file() -> bytes:
    """A document-level attachment in the EmbeddedFiles name tree."""
    document = Document()
    fonts = font_resources(document)
    payload = b"SYNTHETIC attachment: invented data only.\n"
    stream = document.add(
        Stream({"Type": Name("EmbeddedFile"), "Subtype": Name("text/plain")}, payload)
    )
    filespec = document.add(
        {"Type": Name("Filespec"), "F": "synthetic.txt", "UF": "synthetic.txt", "EF": {"F": stream}}
    )
    names = document.add({"EmbeddedFiles": {"Names": ["synthetic.txt", filespec]}})
    return _assemble(
        "embedded-file",
        "SYNTHETIC attachment",
        [PageSpec(_note_page("attachment", "A text file is attached to this document."))],
        document=document,
        fonts=fonts,
        catalog_extra={"Names": names},
    )


def build_tagged_structure() -> bytes:
    """A tagged PDF: one paragraph structure element over marked content."""
    document = Document()
    fonts = font_resources(document)
    page_ref = document.reserve()
    root = document.reserve()
    paragraph = document.add(
        {"Type": Name("StructElem"), "S": Name("P"), "P": root, "Pg": page_ref, "K": 0}
    )
    document.set(
        root,
        {"Type": Name("StructTreeRoot"), "K": paragraph,
         "ParentTree": {"Nums": [0, [paragraph]]}, "ParentTreeNextKey": 1},
    )
    content = (
        b"/P << /MCID 0 >> BDC\n"
        + _note_page("tagged document", "This paragraph is tagged for assistive technology.")
        + b"EMC\n"
    )
    return _assemble(
        "tagged-structure",
        "SYNTHETIC tagged",
        [PageSpec(content, extra={"StructParents": 0})],
        document=document,
        fonts=fonts,
        catalog_extra={"StructTreeRoot": root, "MarkInfo": {"Marked": True}},
        page_refs=[page_ref],
    )


def build_optional_content() -> bytes:
    """A layer (optional content group) that is hidden by default."""
    document = Document()
    fonts = font_resources(document)
    layer = document.add({"Type": Name("OCG"), "Name": "SYNTHETIC hidden layer"})
    content = _note_page("layered document", "One layer of this page is hidden by default.")
    content += (
        b"/OC /L1 BDC\n"
        + text_operators([TextLine(72, 600, 11, "SYNTHETIC hidden layer text", "F1")])
        + b"EMC\n"
    )
    return _assemble(
        "optional-content",
        "SYNTHETIC optional content",
        [PageSpec(content, resources={"Properties": {"L1": layer}})],
        document=document,
        fonts=fonts,
        catalog_extra={
            "OCProperties": {"OCGs": [layer], "D": {"Order": [layer], "OFF": [layer]}}
        },
    )


def build_orphan_javascript() -> bytes:
    """A JavaScript action object that nothing in the document references.

    No conforming reader runs it, but its presence means a different parser
    or an earlier revision may see a script: inspection cannot call the
    document free of active content.
    """
    document = Document()
    fonts = font_resources(document)
    _javascript(document, "/* SYNTHETIC */ var unreferenced = true;")
    return _assemble(
        "orphan-javascript",
        "SYNTHETIC unreferenced script",
        [PageSpec(_note_page("note", "Balance 56.78 on 2026-01-07."))],
        document=document,
        fonts=fonts,
    )


def build_blank_page() -> bytes:
    """Three pages: text, an empty page, and text."""
    return _assemble(
        "blank-page",
        "SYNTHETIC with blank page",
        [
            PageSpec(_statement_page(400, "page 1 of 3")),
            PageSpec(b""),
            PageSpec(_statement_page(402, "page 3 of 3")),
        ],
    )


def build_vector_only() -> bytes:
    """A vector bar chart with no text layer at all."""
    rng = random.Random(11)
    content = bytearray(_rule(72, 100, 540, 100, 1.0) + _rule(72, 100, 72, 700, 1.0))
    for index in range(12):
        height = rng.randrange(80, 580)
        content += _box(90 + index * 38, 100, 26, height, 0.25 + 0.05 * (index % 6))
    return _assemble("vector-only", "SYNTHETIC vector chart", [PageSpec(bytes(content))])


def build_text_unmapped() -> bytes:
    """Text drawn with a Type 3 font whose codes map to no Unicode text.

    The page shows glyphs, but extraction yields only control characters, so
    the page has text objects without a usable text layer.
    """
    document = Document()
    glyph = b"500 0 0 0 400 600 d1 0 0 400 600 re f"
    procs = {name: document.add(Stream({}, glyph)) for name in ("g1", "g2", "g3")}
    font = document.add(
        {
            "Type": Name("Font"),
            "Subtype": Name("Type3"),
            "FontBBox": [0, 0, 500, 700],
            "FontMatrix": [0.001, 0, 0, 0.001, 0, 0],
            "CharProcs": procs,
            "Encoding": {"Type": Name("Encoding"), "Differences": [1, Name("g1"), Name("g2"), Name("g3")]},
            "FirstChar": 1,
            "LastChar": 3,
            "Widths": [500, 500, 500],
            "Resources": {},
        }
    )
    content = b"BT /T3 24 Tf 72 700 Td <010203010203> Tj ET\n"
    return _assemble(
        "text-unmapped",
        "SYNTHETIC unmapped text",
        [PageSpec(content, resources={"Font": {"T3": font}})],
        document=document,
        fonts={},
    )


def build_malformed_truncated() -> bytes:
    """The multipage fixture cut short: no xref table or trailer survives."""
    complete = build_text_multipage()
    return complete[: int(len(complete) * 0.55)]


def build_malformed_bad_xref() -> bytes:
    """Objects intact but every xref offset and startxref are wrong."""
    complete = build_text_statement()
    head, _, tail = complete.rpartition(b"startxref\n")
    offset = int(tail.split(b"\n", 1)[0])
    broken_tail = f"{offset + 97}\n%%EOF\n".encode("ascii")
    table_start = head.index(b"xref\n")
    rebuilt = []
    for line in head[table_start:].split(b"\n"):
        if line.endswith(b" 00000 n "):
            rebuilt.append(f"{int(line[:10]) + 13:010d} 00000 n ".encode("ascii"))
        else:
            rebuilt.append(line)
    return head[:table_start] + b"\n".join(rebuilt) + b"startxref\n" + broken_tail


def build_malformed_not_pdf() -> bytes:
    return (
        b"SYNTHETIC: this file has a .pdf name but is plain text.\n"
        b"It exercises the input-rejection path.\n"
    )


# --------------------------------------------------------------------------
# Catalog
# --------------------------------------------------------------------------

FIXTURES: tuple[FixtureSpec, ...] = (
    FixtureSpec(
        "text-statement",
        "Ordinary text",
        "Single text page with three standard fonts, a numeric table, and rules.",
        ("text-layer", "standard-fonts", "vector-lines"),
        True,
        "Compresses; standard fonts get embedded, so output can grow.",
        True,
        build_text_statement,
    ),
    FixtureSpec(
        "text-multipage",
        "Ordinary text",
        "Twelve distinct pages mixing Letter, A4, landscape, and /Rotate 90.",
        ("text-layer", "multi-page", "mixed-geometry", "rotation"),
        True,
        "Compresses; Ghostscript folds /Rotate into the MediaBox; the product checks page "
        "count only.",
        True,
        build_text_multipage,
    ),
    FixtureSpec(
        "outline",
        "Feature inventory",
        "The twelve-page statement plus a two-entry outline (bookmarks).",
        ("text-layer", "multi-page", "mixed-geometry", "rotation", "outline"),
        True,
        "Compresses; the outline is not inspected or validated.",
        True,
        build_outline,
        preflight="blocked",
    ),
    FixtureSpec(
        "text-tiny",
        "Local detail",
        "3.5-6 pt digits, 0.1 pt hairlines, and a barcode-like bar pattern.",
        ("text-layer", "small-text", "line-art"),
        True,
        "Compresses; small-text legibility is not specifically checked.",
        True,
        build_text_tiny,
    ),
    FixtureSpec(
        "image-scan",
        "Scans",
        "Two image-only grayscale pages at 150 dpi with bitmap text and no text layer.",
        ("image-only", "no-text-layer", "jpeg"),
        False,
        "Compresses by re-encoding or downsampling the page images.",
        True,
        build_image_scan,
    ),
    FixtureSpec(
        "image-mixed",
        "Scans",
        "Two pages combining a text layer with an embedded RGB photograph.",
        ("text-layer", "jpeg", "rgb-image"),
        True,
        "Compresses; the text layer is expected to survive.",
        True,
        build_image_mixed,
    ),
    FixtureSpec(
        "already-small",
        "Already fits",
        "A one-page note far below any realistic ceiling.",
        ("text-layer",),
        True,
        "Still rewritten by Ghostscript; no unchanged-bytes fast path, and the rewrite "
        "is larger than the input because standard fonts get embedded.",
        True,
        build_already_small,
    ),
    FixtureSpec(
        "encrypted-user-password",
        "Feature inventory",
        "RC4-128 encryption requiring a user password to open.",
        ("encrypted",),
        True,
        "Rejected before Ghostscript runs: password-protected.",
        False,
        build_encrypted_user_password,
        preflight="blocked",
    ),
    FixtureSpec(
        "encrypted-owner-only",
        "Feature inventory",
        "RC4-128 encryption with an empty user password (opens without a prompt).",
        ("encrypted", "empty-user-password"),
        True,
        "Rejected before Ghostscript runs, although no password is needed to open it.",
        False,
        build_encrypted_owner_only,
        preflight="blocked",
    ),
    FixtureSpec(
        "form-acroform",
        "Feature inventory",
        "AcroForm with a filled text field and a checked checkbox, with appearances.",
        ("text-layer", "acroform", "widgets"),
        True,
        "Not inspected; Ghostscript drops the AcroForm and flattens field values into "
        "page content, without a warning.",
        True,
        build_form,
        preflight="blocked",
    ),
    FixtureSpec(
        "annotations",
        "Feature inventory",
        "Link (URI), sticky-note, and highlight annotations on a text page.",
        ("text-layer", "annotations", "link"),
        True,
        "Not inspected; Ghostscript 10.02 keeps these annotation types (-dPreserveAnnots).",
        True,
        build_annotations,
        preflight="blocked",
    ),
    FixtureSpec(
        "signed-pkcs7",
        "Feature inventory",
        "Approval signature (adbe.pkcs7.detached) by a disposable, seed-derived test signer.",
        ("text-layer", "acroform", "signature"),
        True,
        "Not inspected; the rewrite no longer carries a signature covering the file, "
        "without a warning.",
        True,
        build_signed,
        preflight="blocked",
    ),
    FixtureSpec(
        "xfa-form",
        "Feature inventory",
        "An AcroForm text field plus an XFA form description stream.",
        ("text-layer", "acroform", "widgets", "xfa"),
        True,
        "Not inspected; Ghostscript does not carry XFA forms.",
        True,
        build_xfa_form,
        preflight="blocked",
    ),
    FixtureSpec(
        "javascript-document",
        "Feature inventory",
        "Document JavaScript in the name tree and as the open action.",
        ("text-layer", "javascript", "open-action"),
        True,
        "Not inspected.",
        True,
        build_javascript_document,
        preflight="blocked",
    ),
    FixtureSpec(
        "page-open-action",
        "Feature inventory",
        "A page open action (/AA /O) that requests a program launch.",
        ("text-layer", "launch-action", "additional-actions"),
        True,
        "Not inspected.",
        True,
        build_page_open_action,
        preflight="blocked",
    ),
    FixtureSpec(
        "embedded-file",
        "Feature inventory",
        "A plain-text attachment in the EmbeddedFiles name tree.",
        ("text-layer", "embedded-file"),
        True,
        "Not inspected.",
        True,
        build_embedded_file,
        preflight="blocked",
    ),
    FixtureSpec(
        "tagged-structure",
        "Feature inventory",
        "A structure tree with one paragraph element over marked content; MarkInfo /Marked.",
        ("text-layer", "tagged"),
        True,
        "Not inspected.",
        True,
        build_tagged_structure,
        preflight="blocked",
    ),
    FixtureSpec(
        "optional-content",
        "Feature inventory",
        "An optional content group (layer) that is hidden by default.",
        ("text-layer", "optional-content"),
        True,
        "Not inspected.",
        True,
        build_optional_content,
        preflight="blocked",
    ),
    FixtureSpec(
        "orphan-javascript",
        "Feature inventory",
        "A JavaScript action object that nothing references.",
        ("text-layer", "unreferenced-object"),
        True,
        "Not inspected.",
        True,
        build_orphan_javascript,
        preflight="inconclusive",
    ),
    FixtureSpec(
        "blank-page",
        "Scans",
        "Three pages: text, an empty page, and text.",
        ("text-layer", "multi-page", "blank-page"),
        True,
        "Compresses.",
        True,
        build_blank_page,
    ),
    FixtureSpec(
        "vector-only",
        "Ordinary text",
        "A vector bar chart with no text layer.",
        ("vector-graphics", "no-text-layer"),
        False,
        "Compresses.",
        True,
        build_vector_only,
    ),
    FixtureSpec(
        "text-unmapped",
        "Text damage",
        "Type 3 glyphs whose character codes map to no Unicode text.",
        ("unmapped-text", "no-usable-text-layer"),
        False,
        "Compresses.",
        True,
        build_text_unmapped,
    ),
    FixtureSpec(
        "malformed-truncated",
        "Runtime",
        "The multipage fixture cut to 55% of its bytes; no xref table or trailer.",
        ("malformed", "truncated"),
        True,
        "Outcome depends on pypdf/Ghostscript recovery; input must stay unchanged.",
        False,
        build_malformed_truncated,
        preflight="unreadable",
    ),
    FixtureSpec(
        "malformed-bad-xref",
        "Runtime",
        "All objects intact, but every xref offset and startxref are wrong.",
        ("malformed", "repairable"),
        True,
        "Usually repaired by pypdf and Ghostscript and compressed.",
        True,
        build_malformed_bad_xref,
    ),
    FixtureSpec(
        "malformed-not-pdf",
        "Runtime",
        "Plain text with a .pdf name.",
        ("malformed", "not-a-pdf"),
        False,
        "Rejected before Ghostscript runs: could not read input PDF.",
        False,
        build_malformed_not_pdf,
        preflight="unreadable",
    ),
)

BY_NAME = {spec.name: spec for spec in FIXTURES}


@lru_cache(maxsize=None)
def fixture_bytes(name: str) -> bytes:
    return BY_NAME[name].build()
